import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Chakra_Petch } from "next/font/google";
import type { Metadata } from "next";

const chakraPetch = Chakra_Petch({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-chakra-petch",
});

export const chakra = chakraPetch.className;

export const metadata: Metadata = {
	title: "revio",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`dark ${GeistSans.variable}`}>
			<body>{children}</body>
		</html>
	);
}
